COLUMN_MAP = {
    "ID задачи": "issue_id",
    "Проект": "project",
    "Теги": "tags",
    "Заголовок": "summary",
    "Заявитель": "reporter",
    "Создана": "created_at",
    "Обновлена": "updated_at",
    "Завершенная": "resolved_at",
    "Статус": "status",
    "Приоритет": "priority",
    "Функциональный заказчик": "functional_customer",
    "Ответственный (ДИТ)": "responsible_dit",
    "Согласование с ДИТ": "approval_dit",
    "Согласование с ГКУ": "approval_gku",
    "Согласование с ДКП": "approval_dkp",
    "Согласование с ДЭПиР": "approval_dep",
    "Тип документа": "doc_type",
    "Действия": "action",
    "Решение ДИТ": "decision_dit",
    "Решение ГКУ": "decision_gku",
    "Решение ДКП": "decision_dkp",
    "Решение ДЭПиР": "decision_dep",
    "StartDIT": "start_dit",
    "StartGKU": "start_gku",
    "StartDKP": "start_dkp",
    "StartDEP": "start_dep",
    "ShowAll": "show_all",
    "ShowDIT": "show_dit",
    "ShowGKU": "show_gku",
    "ShowDKP": "show_dkp",
    "ShowDEP": "show_dep",
    "Changed": "changed",
    "StatesCode": "states_code",
    "Инициатор согласования": "approval_initiator",
    "Срок согласования (ДИТ)": "deadline_dit",
    "Срок согласования (ДКП)": "deadline_dkp",
    "Срок согласования (ДЭПиР)": "deadline_dep",
    "Срок согласования (ГКУ)": "deadline_gku",
    "Срок устранения замечаний": "deadline_fix_comments",
    "Первоначальный срок рассмотрения": "initial_review_deadline",
    "Внутренний согласующий от ДЭПиР": "internal_dep_approver",
    "Согласование с \"Ценовыми справочниками, ПЦП\"": "approval_price_refs",
    "Согласование с \"АРМ Эксперта\"": "approval_arm_expert",
    "Согласование со \"Стандартизацией\"": "approval_standardization",
    "Описание": "description",
    "Голоса": "votes",
}

CORE_FIELDS = [
    "issue_id",
    "project",
    "summary",
    "status",
    "priority",
    "doc_type",
    "functional_customer",
    "responsible_dit",
    "approval_initiator",
    "description",
]
